name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Download the NDI SDK
      run: wget http://new.tk/NDISDKLINUX && tar -xvf NDISDKLINUX
    - name: Install the NDI SDK
      run: yes | bash ./InstallNDISDK_v4_Linux.sh > /dev/null
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: devolay-java/build/libs