name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: sudo apt install mingw-w64

    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Download the NDI SDK
      run: wget http://new.tk/NDISDKLINUX && tar -xvf NDISDKLINUX
    - name: Install the NDI SDK
      run: yes | ./InstallNDISDK_v4_Linux.sh > /dev/null

    - uses: actions/cache@v2
      id: cache
      with:
        path: osxcross
        key: ${{ runner.os }}-osxtoolchain

    # Setup osxcross, as detailed here: https://github.com/andrew-d/docker-osxcross/blob/master/Dockerfile
    - name: Setup OSXCross
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        git clone -n https://github.com/tpoechtrager/osxcross.git
        cd osxcross
        git checkout 364703ca0962c4a12688daf8758802a5df9e3221
        sudo apt update
        sudo ./tools/get_dependencies.sh
        curl -L -o ./tarballs/MacOSX10.15.sdk.tar.xz https://github.com/xorrior/osxsdk/raw/master/MacOSX10.15.sdk.tar.xz
        yes | PORTABLE=true ./build.sh
        yes | PORTABLE=true ./build_binutils.sh
    - name: Add OSXCross to path
      run: |
        export PATH=$PATH:./osxcross/target/bin

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble -DandroidNdk=/usr/local/lib/android/sdk/ndk-bundle

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: devolay-java/build/libs