name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name:
      run: sudo apt install mingw-w64
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Download the NDI SDK
      run: wget http://new.tk/NDISDKLINUX && tar -xvf NDISDKLINUX
    - name: Install the NDI SDK
      run: yes | ./InstallNDISDK_v4_Linux.sh > /dev/null

    # Setup osxcross, as detailed here: https://github.com/andrew-d/docker-osxcross/blob/master/Dockerfile
    - name: Setup OSXCross
      run: >
      git clone https://github.com/tpoechtrager/osxcross.git &&
      cd osxcross &&
      git checkout 474f359d2f27ff68916a064f0138c9188c63db7d &&
      sed -i -e 's|-march=native||g' ./build_clang.sh ./wrapper/build.sh &&
      ./tools/get_dependencies.sh &&
      curl -L -o ./tarballs/MacOSX10.15.sdk.tar.xz https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.15.sdk.tar.xz &&
      yes | PORTABLE=true ./build.sh &&
      ./build_compiler_rt.sh &&
      export PATH=$PATH:./target/bin

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble -DandroidNdk=/usr/local/lib/android/sdk/ndk-bundle

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: devolay-java/build/libs